services:
  db:
    image: postgres:16
    container_name: doctor_booking_db
    environment:
      POSTGRES_DB: doctor_booking
      POSTGRES_USER: doctor_user
      POSTGRES_PASSWORD: doctor_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
